# Generated by Django 4.2.4 on 2023-08-08 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_info_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info_user',
            name='password',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
