# Generated by Django 4.2.4 on 2023-08-08 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quiz_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=255, unique=True)),
                ('password', models.PositiveIntegerField(default=0)),
                ('date_time', models.DateField(auto_now_add=True)),
                ('send_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
