# Generated by Django 4.2.4 on 2023-08-08 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_info_user_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info_user',
            name='date_time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
