# Generated by Django 4.2.4 on 2023-08-10 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_alter_info_user_date_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Info_User',
        ),
        migrations.AddField(
            model_name='leaduser',
            name='active',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='leaduser',
            name='date_time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='leaduser',
            name='password',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='leaduser',
            name='send_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
